project:
  type: website
  output-dir: ../articles

website:
  title: ""
  navbar:
    right:
      - icon: github
        href: https://github.com/timgestson/proofs-args-and-zk
format:
  html:
    theme: flatly
    css: styles.css
